from django.db import models
from django.contrib.auth.models import User
import uuid

class ExamSession(models.Model):
    # Links the session to a specific logged-in user (Student)
    student = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    
    # The UUID generated by your frontend (crypto.randomUUID)
    session_id = models.UUIDField(unique=True, editable=False)
    
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(null=True, blank=True)
    
    # Track overall stats
    total_violations = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"Session {self.session_id} - {self.student}"

class ViolationLog(models.Model):
    session = models.ForeignKey(ExamSession, on_delete=models.CASCADE, related_name='violations')
    timestamp = models.DateTimeField(auto_now_add=True)
    violation_type = models.CharField(max_length=50)
    
    # Angles
    pitch = models.FloatField()
    yaw = models.FloatField()
    roll = models.FloatField()

    # --- NEW: Evidence Snapshot ---
    # Requires: pip install Pillow
    snapshot = models.ImageField(upload_to='violations/%Y/%m/%d/', null=True, blank=True)

    def __str__(self):
        return f"{self.violation_type} - {self.timestamp}"